#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit facebook youtube weather apps cava mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--fde" ]]; then
	close_dash && firefox-developer-edition &

elif [[ "$1" == "--nvim" ]]; then
	close_dash && OpenApps --nvim &

elif [[ "$1" == "--dc" ]]; then
	close_dash && discord &

elif [[ "$1" == "--code" ]]; then
	close_dash && code &
^
elif [[ "$1" == "--qbit" ]]; then
	close_dash && qbittorrent &

elif [[ "$1" == "--charm" ]]; then
	close_dash && pycharm &

fi
